### ISSUE TITLE
[BUG] coreMQTT keep alive handling fails and never reconnects

### ISSUE THREAD

**Issue by lhammond** [FreeRTOS/iot-reference-esp32c3#48] opened 2023-09-05 16:53 UTC
**Describe the bug**
Please provide a clear and concise description explaining the bug.

**System information**
- Hardware board: [ esp32s3 (Seeed Xiao) ]
- IDE used: [ VSCode ]
- Operating System: [ MacOS ]
- Code version: (v202212.00-23-gd25036b
- Project/Demo: [ Temperature LED demo with AWS pub/sub ]

**Expected behavior**
Expected behavior would be for the MQTT subsystem to continue retries until reconnected.

**Screenshots or console output**
<img width="986" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/a6ed4efc-427e-42b8-95bf-101e1a4c9801">

**Steps to reproduce bug**
    Example:
      1. "I am using project [ ... ], and have configured with [ ... ]"
      2. "When run on [ ... ], I observed that [ ... ]"

**Code to reproduce bug**
```cpp
idf.py -p /dev/cu.usbmodem14101 flash monitor
```

**Comment by Skptak** [comment] 2023-09-06 00:12
Hey @lhammond, thanks for submitting this issue!
It appears this is an issue many people are running since #41, #45, #46, and #47 all appear to similar issues with the coreMQTT connection to the AWS IoT broker.

I've reached out to the team that works directly with coreMQTT and with the ESP32 boards to see if we can get to the bottom of what is causing these issues.

**Comment by lhammond** [comment] 2023-09-06 02:42
Hello :) and thank you.
We have a small batch of production hardware that needs this fix and are
eager to support resolution.
cheers from our team!

**Comment by lhammond** [comment] 2023-09-11 14:56
@Skptak Is there anything we can do to help push towards resolution?  Should I be monitoring this situation in another place?  Thank you!

**Comment by rawalexe** [comment] 2023-09-11 23:46
@lhammond,
Can you please give a bit more insight on the problem, what version of esp-idf are you using? have you flashed your credential to the device and is your Thing name and endpoint at the correct account? Did you provision your device? 

I was not able to reproduce your problem and here is a small sectional screenshot of my logs 
![Screenshot 2023-09-11 at 4 44 40 PM](https://github.com/FreeRTOS/iot-reference-esp32c3/assets/113639451/73b1d101-be13-4283-a6a0-26b17cd69420)

**Comment by rawalexe** [comment] 2023-09-12 01:40
Can you also please passte your skdconfig file for s3

**Comment by gavin-hy** [comment] 2023-09-12 09:33
@rawalexe  Have you tested it over a long period of time?
When I tested it, this happened within four hours! When I reconfigured the network it was able to reconnect to broke, but the above problem still occurred after a while. There is another problem. After I unplug the AP's network cable, after a while, I plug it in again and it will no longer be able to actively report information.
Below is a screenshot of my log and sdkconfig.
![1694506767402](https://github.com/FreeRTOS/iot-reference-esp32c3/assets/111403234/5bcba995-3c99-43df-a02d-3069f0344a91)
![1694507127378](https://github.com/FreeRTOS/iot-reference-esp32c3/assets/111403234/4231953d-12c3-4d83-8d81-4382ae17afc2)

![1694507127363](https://github.com/FreeRTOS/iot-reference-esp32c3/assets/111403234/6ac876c3-ffba-465e-aecd-abacca1b0287)
![image](https://github.com/FreeRTOS/iot-reference-esp32c3/assets/111403234/0bae7563-b855-4294-9c59-2e8810f729b9)

**Comment by lhammond** [comment] 2023-09-12 15:28
Hi @rawalexe you can see the version at the top of this issue thread .. v202212.00-23-gd25036b
I am using the LED pub sub demo, not OTA.

You will see the issue I'm experiencing in the screenshot in the original post.  If left alone, the device eventually disconnects and continues to output the "no command structure" forever.

**Comment by lhammond** [comment] 2023-09-12 22:56
@gavin-hy what MCU are you running?

**Comment by lhammond** [comment] 2023-09-12 22:59
Hey @Skptak .. I'm away from my lab for a day and will try the potential fix you mention upon return.  Thanks!

**Comment by gavin-hy** [comment] 2023-09-13 01:04
> @gavin-hy what MCU are you running?

ESP32-C3

**Comment by rawalexe** [comment] 2023-09-14 17:47
> Hi @rawalexe you can see the version at the top of this issue thread .. v202212.00-23-gd25036b I am using the LED pub sub demo, not OTA.
> 
> You will see the issue I'm experiencing in the screenshot in the original post. If left alone, the device eventually disconnects and continues to output the "no command structure" forever.

I am running all the demos, if you look into my attached screenshot. I'll try to replicate your issue by just running the temp sub pub over long period of time.

**Comment by lhammond** [comment] 2023-09-14 18:27
great, thank you very much.

**Comment by anubhavrawal** [comment] 2023-09-15 00:37
@lhammond can you please provide your whole skdconfig file for S3. With your endpoint removed. So that I have a 1-1 for replication your issue for S3. 

Thank you,
AR

**Comment by rawalexe** [comment] 2023-09-15 21:42
Hello @lhammond @gavin-hy,
I've tried killing the connection and then bring it back up, keeping it alive for long hours and am still not able to reproduce the bug.
![Screenshot 2023-09-15 at 2 38 07 PM](https://github.com/FreeRTOS/iot-reference-esp32c3/assets/113639451/48d87fd4-2d32-4cf7-b71f-2e339421759a)

Have you changed the code to any degree? Can you please send me a zip of your repo?

Best Regards,
AR

**Comment by lhammond** [comment] 2023-09-19 15:32
@Skptak there was no change in behavior by changing the TLS Transport Send / Receive timeout to 10000

**Comment by lhammond** [comment] 2023-09-19 15:33
@rawalexe yes, I have made some modifications.  How can I send you the zip file?

**Comment by lhammond** [comment] 2023-09-19 15:34
> @lhammond can you please provide your whole skdconfig file for S3. With your endpoint removed. So that I have a 1-1 for replication your issue for S3.
> 
> Thank you, AR

I am not using OTA demo nor S3 .. do you still need the sdkconfig?

**Comment by anubhavrawal** [comment] 2023-09-19 15:35
Can you please email it to me. It's rawalexe@amazon.com.

**Comment by lhammond** [comment] 2023-09-19 15:51
@rawalexe @anubhavrawal It's too big to email, I just shared a google drive link to your email .. let me know if you can't down load it.  I'm happy to get on a google meet if you'd like

**Comment by rawalexe** [comment] 2023-09-19 16:07
@lhammond ,
Thank you for sharing the code, I was running all the demos to see if any other fail as well. However, for my other runs I disabled the demos from menuconfig and proceeded with the possible replication process of killing the internet connection. 

Thank you for the file, I was able to download it and will try to replicate it today. I'll keep you posted on my progress

Best Regards,
AR

**Comment by rawalexe** [comment] 2023-09-21 02:07
@lhammond 
Can you please provide me with a little bit more context in this repo as some of things that I immediately notice is that you are not using the the right tag that you mentioned at the start o the ticket, you are on the main branch, also what's your esp-idf version number?


If you try to use the tagged version at commit `2dccbca`  with esp-idf 4.4.5  commit `ac5d805d0e` do you still see the issue?

Best Regards,
AR

**Comment by lhammond** [comment] 2023-09-21 13:11
@rawalexe 
`bash-3.2$ idf.py --version
ESP-IDF v5.0.3-230-g35c484324f-dirty`

I will try with the versions above and let you know

**Comment by lhammond** [comment] 2023-09-21 13:50
@rawalexe when I try building the branch, cmake fails to resolve component esp_secure_cert_mgr. The folder is there, but it is empty.

<img width="445" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/b69e0a1b-89d1-41a6-a379-5507c1dd5af6">

<img width="386" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/f4483872-76df-474f-aef4-0f9adcac61ef">

<img width="643" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/4113169b-57d0-48e5-8a33-112107d83ebc">

my steps :

- git clone https://github.com/espressif/esp-idf.git
- cd esp-idf
- git checkout ac5d805d0e
- install.sh
- export.sh
- brew install cmake ninja
- git clone https://github.com/FreeRTOS/iot-reference-esp32c3.git iot-reference-esp32c3-rawalexe-help --recurse-submodules
- cd iot-reference-esp32c3-rawalexe-help
- git checkout 2dccbca
- export IDF_TARGET=esp32s3
- idf.py set-target esp32s3

**Comment by lhammond** [comment] 2023-09-21 14:04
@rawalexe I am preparing to test with the new versions.  I did want to point out that I am using a NeoPixel ring with (RMT - Addressable LED ) .. this option does not appear in menuconfig for commit 2dccbca.  I'm guessing all of that functionality is implemented in the the demo's .c or app_driver.c and I can port it over.

<img width="631" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/e1318e8e-a557-41e7-b750-58615ef45ff9">

**Comment by lhammond** [comment] 2023-09-21 14:37
@rawalexe After adding `component_compile_options(-Wno-error=format= -Wno-format)` to the bottom of main/CMakeLists.txt apparently due to https://github.com/espressif/esp-idf/issues/9511#issuecomment-1207322098 

I am seeing the below

<img width="1411" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/1f0809a3-b059-4e7e-8ed7-687ff346a4e1">

**Comment by lhammond** [comment] 2023-09-21 19:05
@rawalexe I kept the publish while(true) loop but commented out the logic and it resolved the above sensor-related error.  I have the pub/sub temperature LED demo running now with the versions you requested.  I started it at 3:03 PM EST .. going to monitor it long term.

**Comment by lhammond** [comment] 2023-09-21 19:28
about 11 minutes into the test I get the following .. I'm leaving it running

<img width="1233" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/08ce73ef-7570-4bf3-a0ee-96a447b156dd">

**Comment by lhammond** [comment] 2023-09-21 19:34
@rawalexe there is no TLS timeout in this version .. but maybe CONNACK is the same .. I made these changes and rerunning the test

<img width="564" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/09bb2e3b-e068-4140-8f50-b7d5e2735135">

**Comment by lhammond** [comment] 2023-09-25 18:11
@rawalexe @anubhavrawal @Skptak 

The versions above with a CONNACK of 10000 has been running for two days.  I commented out the publish logic inside the while(true) loop. 

So the question is, do I back port the LED demo logic to this version or is there a plan to fix latest branches to address the connectivity issue?

thanks

**Comment by rawalexe** [comment] 2023-09-25 18:21
Hello @lhammond,
I see that there are few bugs in the repo, but it will take us sometime to look more into it and find a fix for this. If you can find the specific bug within the repo and submit a PR the team will be happy to merge a permanent fix, and will be the quickest fix.

Best Regards,
AR

**Comment by lhammond** [comment] 2023-09-25 18:25
@rawalexe ok, I'll see what I can do.  I need to push these production devices out asap, so will probably backport the LED control logic first and will try to find some time to look around for the connectivity issue.  Do you have an idea of which repo to look in?  Is it a submodule or in this repo?  

Would you guys be looking to apply any fixes to version 5.x?

**Comment by txf-** [comment] 2023-09-28 10:33
I can say that the commit d25036b is definitely the cause of it not reconnecting. I had previously reported here https://github.com/FreeRTOS/iot-reference-esp32c3/issues/34#issuecomment-1513129335, when it was still a patch. 

Reverting after reverting the changes to the previous version of the agent manager, the device reconnected

**Comment by rawalexe** [comment] 2023-10-01 22:01
Hello @lhammond  @txf-,
I have created this repo and tested out on my local device, can either of you test out to fit in your use cases?

https://github.com/rawalexe/iot-reference-esp32c3/tree/newEsp

It has few updated instructions and esp-idf v5.1.1 submodule

Best Regards,
AR

**Comment by lhammond** [comment] 2023-10-01 22:19
I'm UTC -5 and will do first thing tomorrow AM.
awesome that you did this.

**Comment by txf-** [comment] 2023-10-01 22:39
The reconnection issues were fixed by the reversion of the optimizations in core_mqtt_agent_manager.c. 

I can't actually tell what changes were made in newEsp that affects this. Is this repo just adjustments to make it work with idf 5.x?

**Comment by rawalexe** [comment] 2023-10-01 22:50
Yes the changes are the documentation on using Amazon's version of FreeRTOS and submodule to latest esp-idf. I did not have any problem building the project or running them so am looking for verification that this works on the previously problematic scenarios.

Best Regards,
AR

**Comment by lhammond** [comment] 2023-10-03 19:46
I'm working on this now .. i'm using a idf.py I had installed already.  Do
I need to install 5.x tools?

**Comment by lhammond** [comment] 2023-10-03 20:03
I do not see the Amazon kernel option in newEsp branch.  Screenshot of
menuconfig below
[image: image.png]

**Comment by rawalexe** [comment] 2023-10-05 05:15
Hello @lhammond ,
you would need at an esp idf 5.0+ to be able to switch kernel version. It should be under `idf menuconfig > Component config > FreeRTOS > Kernel> Run the Amazon SMP FreeRTOS kernel instead (FEATURE UNDER DEVELOPMENT)`

I would recommend using the submoduled  esp-idf for standardization purpose but any 5.0+ idf should mostly behave the similar.

 Thank you

Best Regards,
AR

**Comment by lhammond** [comment] 2023-10-06 15:57
@rawalexe ok, finally got it sorted and just started a long running test.  stay tuned!

**Comment by lhammond** [comment] 2023-10-06 16:02
this happened after about 20 seconds.  I'm going to double check the timeout and try again 

<img width="929" alt="image" src="https://github.com/FreeRTOS/iot-reference-esp32c3/assets/229602/70227878-221a-4849-bd4a-1c524b73bc5d">

**Comment by rawalexe** [comment] 2023-10-08 15:49
That's. quite unfortunate, Give me some time I'll spend some time to see if I we can fix this.

Best Regards,
AR

**Comment by lhammond** [comment] 2023-11-13 17:20
Hi @rawalexe .. I'm back on this project again.  Have you made any progress?

**Comment by anubhavrawal** [comment] 2023-11-13 17:30
Hello @lhammond,
We forwarded this issue to espressif as they wanted this to be compatible with all the esp-idf versions 4.4+. I'll keep you posted once we hear back from them.

**Comment by rawalexe** [comment] 2023-11-18 00:27
Hello @lhammond ,
After talking with espressif, they mentioned that adding process loop was indeed a known problem and noticed that the file you sent us didn't contain the commit reverting the process loop, commit id : `f4fe11e27a7d686b7a2f22de278ece570b692ce9`. I apologize to ask you to run these on different condition but just want to make sure that the known issues aren't creating any problems.  Can you please make sure that you are using the latest changes in the main and still facing the issues? I attempted these changes on my device, didn't replicate test for long hours though and the demo ran as expected for 30 mins or so.

Best Regards,
AR

**Comment by lhammond** [comment] 2023-11-27 17:37
ok thanks .. is that commit hash for the main repo, or for the fork you
created for me to test previously?

**Comment by lhammond** [comment] 2023-12-15 17:37
@rawalexe The LED/temperature demo has been running with that commit id for about 3.5 days.  I have not yet tried pulling the AP's network cable to check behavior, but this is encouraging.  I will try that test sometime this weekend.

**Comment by rawalexe** [comment] 2023-12-19 22:44
Hello @lhammond,
That's a great news, and yes you do understand it correctly. Please let us know if this resolves your problem so that we can close the issue appropriately.

Best Regards,
AR

**Comment by rawalexe** [comment] 2023-12-27 16:15
As there is no further concern from you, I am closing this issue as resolved, if the problem persists please feel free to reopen the issue or open a new one.

**Closed by rawalexe** 2023-12-27 16:15 UTC
